spring.application.name=PROJECT-MANAGEMENT
spring.cloud.config.fail-fast=true

server.port=8084


spring.h2.console.enabled=true
spring.h2.console.path=/h2


spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:file:./projectDB
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.cloud.config.enabled=false
# Email configuration for Postfix
spring.mail.host=postfix
spring.mail.port=25
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false